def custom_font():
    from fontstyle import apply
    string=input('Enter the string: ')
    l=len(string)
    for _ in range(l):
        c=string[_].upper()
        if c=='A':
            print("     #")
            print("   #   #")
            print("  #######")
            print(" #       #")
            print("#         #")
        elif c=='B':
            print("####")
            print("#  #")
            print("# #")
            print("#  #")
            print("#####")
        elif c=='C':
            print(" #####")
            print("#")
            print("#")
            print("#")
            print(" #####")
        elif c=='D':
            print("#####")
            print("#    #")
            print("#    #")
            print("#    #")
            print("#####")
        elif c=='E':
            print("######")
            print("#")
            print("######")
            print("#")
            print("######")
        elif c=='F':
            print("######")
            print("#")
            print("######")
            print("#")
            print("#")
        elif c=='G':
            print(" #####")
            print("#")
            print("#  ###")
            print("#    #")
            print(" #####")
        elif c=='H':
            print("#    #")
            print("#    #")
            print("######")
            print("#    #")
            print("#    #")
        elif c=='I':
            print("######")
            print("  ##")
            print("  ##")
            print("  ##")
            print("######")
        elif c=='J':
            print("######")
            print("  ##")
            print("  ##")
            print("  ##")
            print("###")
        elif c=='K':
            print(".....#.....")
            print("...#...#...")
            print("..#######..")
            print(".#.......#.")
            print("#.........#")
        elif c=='L':
            print("#")
            print("#")
            print("#")
            print("#")
            print(" #####")
        elif c=='M':
            print(".....#.....")
            print("...#...#...")
            print("..#######..")
            print(".#.......#.")
            print("#.........#")
        elif c=='N':
            print(".....#.....")
            print("...#...#...")
            print("..#######..")
            print(".#.......#.")
            print("#.........#")
        elif c=='O':
            print("######")
            print("#    #")
            print("#    #")
            print("#    #")
            print("######")
        elif c=='P':
            print("######")
            print("#    #")
            print("######")
            print("#")
            print("#")
            
        elif c=='Q':
            print("######")
            print("#    #")
            print("#  # #")
            print("#   ##")
            print("######")
            print("      #")
        elif c=='R':
            print("#####")
            print("#  #")
            print("# #")
            print("#  #")
            print("#   #")
        elif c=='S':
            print("######")
            print("#")
            print("######")
            print("     #")
            print("######")
        elif c=='T':
            print("######")
            print("  ##")
            print("  ##")
            print("  ##")
            print("  ##")
        elif c=='U':
            print("#    #")
            print("#    #")
            print("#    #")
            print("#    #")
            print(" ####")
        elif c=='V':
            print("#         #")
            print(" #       #")
            print("  #     #")
            print("   #   #")
            print("     #")
        elif c=='W':
            print("#           #")
            print(" #         #")
            print("  #   #   #")
            print("   # # # #")
            print("    #   #")
        elif c=='X':
            print("#       #")
            print("  #   #")
            print("    #")
            print("  #   #")
            print("#       #")
        elif c=='Y':
            print("#       #")
            print("  #   #")
            print("    #")
            print("    #")
            print("    #")
        elif c=='Z':
            print("######")
            print("    #")
            print("  #")
            print("#")
            print("######")